### PR TITLE
Fix typo in earlier post

### PR DESCRIPTION
**Pull request by yitznewton**

### CODE REVIEW

**Comment by nwp** [comment]
Welcome back @yitznewton!

**Comment by yitznewton** [comment]
Oops, I just saw the [correct branch naming convention](https://github.com/mdx-dev/platform-api/wiki/Platform-Team-Survival-Guide#branch-and-pull) -- mea culpa.

**Comment by yitznewton** [comment]
Thank you @nwp !!!

**Comment by elijahsummers** [comment]
:+1:

**Comment by blainesch** [comment]
:+1: merge it!

**Pull request merged**
